services:
  project-db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: boilerplate 
      POSTGRES_DB: boilerplate 
    volumes:
      - boilerplate-db-data:/var/lib/postgresql/data
      - ./database-init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025

  redis:
    image: redis:7.4.7-alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
      - boilerplate-redis-data:/data

volumes:
  boilerplate-db-data:
    driver: local
  boilerplate-redis-data:
    driver: local
